### ISSUE TITLE
Tags? Releases?

### ISSUE THREAD

**Issue by ioleo** [Wisembly/ExcelAnt#9]
This bundle looks very promising and I'll definitely give it a try, but what worries me is that there are no tags or roadmap where I could find info on when a stable release will be ready? Or is dev-master already stable?

**Comment by guillaumepotier** [comment]
Hi there,

master branch is already stable, we currently use it in production for Wisembly. We'll add some tags.

Best

cc @rgazelot

**Comment by guillaumepotier** [comment]
done

**Comment by ioleo** [comment]
thanks!
